name: Deploy to AWS S3

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1 

      - name: Verify AWS Access
        run: |
          aws sts get-caller-identity  # Should show your IAM user
          aws s3 ls s3://awss3staticgithubaction  # Should list bucket contents

      - name: Upload index.html
        run: |
          echo "<h1>Hello World from AWS S3</h1>" > index.html
          aws s3 cp index.html s3://awss3staticgithubaction/

      - name: Sync files to S3
        run: |
          aws s3 sync ./ s3://awss3staticgithubaction \
            --delete \
            --exclude '.git/*' \
            --exclude '.github/*'
